<a href="https://colab.research.google.com/github/PujanPandey07/Deep-Learning-/blob/main/startingwithpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors   
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# vector
vector=torch.tensor([7,7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,7],[8,9]])
MATRIX

tensor([[7, 7],
        [8, 9]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

In [16]:
TENSOR[0][0][0]

tensor(1)

## Random Tensors

Why Random Tensors?
Tensors are used in PyTorch because they efficiently represent multi-dimensional data and support GPU computation and automatic differentiation, while random tensors are used to initialize weights, introduce stochasticity, and enable effective learning in neural networks.

In [17]:
# create a random Tensor
random_tensor=torch.rand(3,4)

In [18]:
random_tensor

tensor([[0.5660, 0.2797, 0.6898, 0.0381],
        [0.3557, 0.1870, 0.6181, 0.9237],
        [0.4626, 0.0824, 0.3962, 0.6335]])

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
#create a random tensor with similar shape to a image tensor
image_tensor=torch.rand(size=(224,224,3))
image_tensor.shape,image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
## Zeroes and Ones
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
##tensor of ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
## A range of tensors
torch.arange(start=0,end=10,step=3)

tensor([0, 3, 6, 9])

## Tensor datatypes
**Note** Tensor datatype is one of the 3 big issues or error area in pytorch and deeplearning .
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on right device

In [25]:
# creating tensors like
ten_zeros=torch.zeros_like(input=ones)
ten_zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
## tensor datatypes
float_32_tensor=torch.tensor([3.0,6.0,9.0])
float_32_tensor
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor=torch.rand(size=(3,4),dtype=torch.float16)
float_16_tensor

tensor([[0.2510, 0.6177, 0.9321, 0.8198],
        [0.0015, 0.6143, 0.8398, 0.3521],
        [0.3813, 0.2251, 0.5713, 0.7383]], dtype=torch.float16)

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
a= torch.tensor([1,2,3,4],dtype=torch.int32)

In [30]:
# find out details about some tensors
print(a)
print(f"Datatype of tensor: {a.dtype}")
print(f"Shape of tensor: {a.shape}")
print(f"Device tensor is on:{a.device}")

tensor([1, 2, 3, 4], dtype=torch.int32)
Datatype of tensor: torch.int32
Shape of tensor: torch.Size([4])
Device tensor is on:cpu


In [31]:
## Manupulating tensors(tensors operations)
tensor=torch.tensor([[1,2,3,4],[2,6,7,8]])
tensor+50

tensor([[51, 52, 53, 54],
        [52, 56, 57, 58]])

In [32]:
tensor*10

tensor([[10, 20, 30, 40],
        [20, 60, 70, 80]])

In [33]:
tensor-10

tensor([[-9, -8, -7, -6],
        [-8, -4, -3, -2]])

In [34]:
## Try out pytorch in built opretions
tensor=torch.tensor([1,2,3,4])
torch.mul(tensor,10)


tensor([10, 20, 30, 40])

In [35]:
torch.add(tensor,100)

tensor([101, 102, 103, 104])

## Matrix multiplication


In [36]:
tensor

tensor([1, 2, 3, 4])

In [37]:
tensor*tensor

tensor([ 1,  4,  9, 16])

In [38]:
torch.matmul(tensor,tensor)

tensor(30)

## One of the most common errors in matrix multiplications shape errors

In [41]:
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,8],[9,10],[10,11]])
torch.matmul(tensor_a,tensor_b)# we can use torch.mm as alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [43]:
## to solve the problem of mismatching shapes we can use transpose one of them
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 23,  29,  32],
        [ 53,  67,  74],
        [ 83, 105, 116]])

## finding the min,max,sum and other aggregations of tensors

In [44]:
tensor=torch.arange(0,100,10)

In [45]:
torch.min(tensor)

tensor(0)

In [46]:
torch.max(tensor)

tensor(90)

In [48]:
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [49]:
# finding the positional mean and max
tensor.argmin()

tensor(0)

In [50]:
tensor.argmax()

tensor(9)


## reshaping,stacking ,squeezing and unsqueezing tensors


*   Reshaping-reshapes the tensor into required shape
*   Stacking-combines multiple tensors on top of each other(vstack) or side by side(hstack)
*   view-returns view of an input tensor of certain shape but keep the same memory as the original tensors
* squeezing- removes all 1 dimensions in tensor
* unsqueezing-adds a 1dimensional tensor










In [52]:
x=torch.arange(1,10)

In [53]:
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [54]:
reshaped_x=x.reshape(1,9)
reshaped_x,reshaped_x.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [55]:
# change the view
x.view(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
x.view(2.9)

TypeError: view() received an invalid combination of arguments - got (float), but expected one of:
 * (torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (!float!)
 * (tuple of ints size)
      didn't match because some of the arguments have invalid types: (!float!)


In [63]:
# stacking
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape,x_stacked.ndim

(tensor([[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]),
 2)

In [64]:
# squeezing
x_squeezed=x_stacked.squeeze()
x_squeezed,x_squeezed.shape,x_squeezed.ndim

(tensor([[1, 1, 1, 1],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]),
 2)

In [69]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
x


tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [67]:
y = torch.squeeze(x)
y.size()


torch.Size([2, 2, 2])

In [68]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [71]:
# permuting
x = torch.randn(2, 3, 5)
x.size()


torch.Size([2, 3, 5])

In [72]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [73]:
#unsquezing
x = torch.tensor([1, 2, 3, 4])
print(f"Original tensor: {x}")
print(f"Original shape: {x.shape}")

# Unsqueeze at dimension 0 to get shape [1, 4]
y = torch.unsqueeze(x, dim=0)
print(f"Unsqueezed at dim 0 shape: {y.shape}")
# Output: Unsqueezed at dim 0 shape: torch.Size([1, 4])

# Unsqueeze at dimension 1 (or -1) to get shape [4, 1]
z = x.unsqueeze(dim=1)
print(f"Unsqueezed at dim 1 shape: {z.shape}")
# Output: Unsqueezed at dim 1 shape: torch.Size([4, 1])

Original tensor: tensor([1, 2, 3, 4])
Original shape: torch.Size([4])
Unsqueezed at dim 0 shape: torch.Size([1, 4])
Unsqueezed at dim 1 shape: torch.Size([4, 1])


In [1]:
## Indexing (selecting data from tensors)
import torch
x=torch.arange(1,10).reshape(1,3,3)


In [2]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
#lets index on our first tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0][0]

tensor([1, 2, 3])

In [6]:
x[0][0][2]

tensor(3)

In [8]:
# get all values of oth and 1st dimension but only one value of second dimension
x[:,:,1]

tensor([[2, 5, 8]])

## pytorch and Numpy

In [9]:
# numpy array to a tensor
import torch
import numpy as np

In [10]:
a=np.arange(1,10)
tensor=torch.from_numpy(a)

In [11]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduciability in Pytorch
In short a Neural Network learns in the following manner:

> start with random numbers -> Apply tensor opreations on these random numbers -> update the initial random numbers for better representation of data -> continue this process.

to reduce randomness in neural networks pytorch comes with the concept of random seeds



In [15]:
import torch
random_tensorA=torch.rand(3,4)
random_tensorB=torch.rand(3,4)
print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)

tensor([[0.7491, 0.3005, 0.0889, 0.9978],
        [0.1831, 0.3236, 0.2858, 0.4022],
        [0.3526, 0.4228, 0.1240, 0.7758]])
tensor([[0.3301, 0.5194, 0.7492, 0.9817],
        [0.4537, 0.6721, 0.7710, 0.2502],
        [0.7061, 0.3415, 0.2646, 0.5804]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [18]:
#reproducible tensors
torch.manual_seed(42)
a=torch.rand(3,4)
torch.manual_seed(42)
b=torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running pythorch objects and tensors on GPUs

In [20]:
torch.cuda.is_available()

False